'use client'
import { useState } from 'react'
import Link from 'next/link'
import { motion } from 'framer-motion'
import {
  Brain, MessageSquare, BarChart3, Briefcase, Shield, Clock,
  Check, ArrowRight, Code, Target, Star, Users, Sparkles,
  TrendingUp, Award, Zap, BookOpen, Layers, Monitor
} from 'lucide-react'
import { cn } from '@/lib/utils'
import { TopNav } from '@/components/ui/top-nav'
import { MarqueeStrip } from '@/components/ui/marquee-strip'
import { ColorBlock } from '@/components/ui/color-block'
import { FigmaButton } from '@/components/ui/figma-button'
import { Footer } from '@/components/ui/footer'

const features = [
  {
    icon: Brain,
    title: 'AI Interview Questions',
    description: 'Dynamic questions generated by AI based on your role, experience, and target company.',
  },
  {
    icon: MessageSquare,
    title: 'Real-time Feedback',
    description: 'Instant feedback on your responses with detailed analysis of content and delivery.',
  },
  {
    icon: BarChart3,
    title: 'Performance Analytics',
    description: 'Comprehensive analytics tracking your progress across multiple dimensions.',
  },
  {
    icon: Briefcase,
    title: 'Role-based Interviews',
    description: 'Tailored interviews for specific roles from SWE to Product Management.',
  },
  {
    icon: Shield,
    title: 'AI Scoring',
    description: 'Multi-dimensional scoring evaluating clarity, relevance, depth, and confidence.',
  },
  {
    icon: Clock,
    title: 'Timed Practice',
    description: 'Real interview pressure with timed sessions and countdown reminders.',
  },
]

const limeFeatures = [
  'Role-specific question banks for every position',
  'Real-time AI feedback on your responses',
  'Performance scoring across multiple dimensions',
  'Company-specific interview preparation',
]

const navyStats = [
  { value: '50K+', label: 'Mock Interviews' },
  { value: '98%', label: 'Success Rate' },
  { value: '500+', label: 'Companies' },
  { value: '10K+', label: 'Active Users' },
]

const coralFeatures = [
  { icon: Code, title: 'Technical Interviews', desc: 'Data structures, algorithms, system design, and coding challenges' },
  { icon: Zap, title: 'System Design Prep', desc: 'Practice designing scalable systems with real-world scenarios' },
  { icon: Target, title: 'Behavioral Coaching', desc: 'STAR method training with personalized feedback loops' },
]

const companyItems = ['Google', 'Meta', 'Amazon', 'Microsoft', 'Apple', 'Netflix', 'Stripe', 'Spotify']

function FadeIn({ children, delay = 0, className }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 24 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: '-80px' }}
      transition={{ duration: 0.6, delay }}
      className={className}
    >
      {children}
    </motion.div>
  )
}

export default function LandingPage() {
  return (
    <div className="w-full min-h-screen bg-white text-black">
      <TopNav />

      {/* ===== HERO ===== */}
      <section className="relative flex min-h-[90vh] flex-col items-center justify-center px-4 pt-14">
        <div className="mx-auto max-w-5xl text-center">
          <FadeIn>
            <p className="mb-6 text-[18px] font-[400] font-mono uppercase tracking-[0.54px] text-black/40">
              AI Mock Interviews
            </p>
          </FadeIn>
          <FadeIn delay={0.15}>
            <h1 className="text-[48px] md:text-[86px] font-[340] leading-[1.00] tracking-[-1.72px] text-black">
              Ace Your Next<br />Interview With AI
            </h1>
          </FadeIn>
          <FadeIn delay={0.3}>
            <p className="mx-auto mt-6 max-w-2xl text-[20px] font-[330] leading-[1.40] tracking-[-0.14px] text-black/60">
              Practice with real-time AI-powered mock interviews. Get instant feedback, track your progress, and land your dream job.
            </p>
          </FadeIn>
          <FadeIn delay={0.45}>
            <div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row">
              <FigmaButton variant="primary" href="/signup">
                Get started for free
                <ArrowRight className="h-4 w-4" />
              </FigmaButton>
              <FigmaButton variant="secondary" href="/interview">
                View demo
              </FigmaButton>
            </div>
          </FadeIn>
          <FadeIn delay={0.6}>
            <div className="mt-20">
              <p className="mb-6 text-[16px] font-[330] text-black/40">
                Trusted by candidates from leading companies
              </p>
              <div className="flex flex-wrap items-center justify-center gap-8">
                {companyItems.map((company) => (
                  <span
                    key={company}
                    className="text-lg font-semibold tracking-wider text-black/20"
                  >
                    {company}
                  </span>
                ))}
              </div>
            </div>
          </FadeIn>
        </div>
      </section>

      {/* ===== MARQUEE ===== */}
      <MarqueeStrip items={companyItems} />

      {/* ===== FEATURES ===== */}
      <section className="py-24">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <FadeIn>
            <h2 className="text-center text-[26px] font-[540] leading-[1.35] tracking-[-0.26px] text-black">
              Everything you need to prepare
            </h2>
          </FadeIn>
          <div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {features.map((feature, index) => (
              <FadeIn key={feature.title} delay={index * 0.05}>
                <div className="rounded-[8px] bg-[#f7f7f5] p-6 transition-all duration-200 hover:bg-[#f0f0ee]">
                  <div className="mb-4 inline-flex rounded-full bg-white p-3">
                    <feature.icon className="h-5 w-5 text-black" />
                  </div>
                  <h3 className="mb-2 text-[20px] font-[480] leading-[1.40] tracking-[-0.10px] text-black">
                    {feature.title}
                  </h3>
                  <p className="text-[16px] font-[330] leading-[1.45] text-black/60">
                    {feature.description}
                  </p>
                </div>
              </FadeIn>
            ))}
          </div>
        </div>
      </section>

      {/* ===== COLOR BLOCK LIME ===== */}
      <section className="py-24">
        <ColorBlock variant="lime">
          <div className="mx-auto max-w-4xl">
            <FadeIn>
              <p className="text-[18px] font-[400] font-mono uppercase tracking-[0.54px] text-black/40">
                Built for every role
              </p>
            </FadeIn>
            <FadeIn delay={0.1}>
              <h2 className="mt-4 text-[26px] font-[540] leading-[1.35] tracking-[-0.26px] text-black">
                Real interviews, real confidence
              </h2>
            </FadeIn>
            <FadeIn delay={0.2}>
              <p className="mt-4 text-[20px] font-[330] leading-[1.40] tracking-[-0.14px] text-black/70 max-w-2xl">
                Our AI platform simulates real interview environments with role-specific questions, 
                timed responses, and instant feedback. Practice until you&apos;re ready for the real thing.
              </p>
            </FadeIn>
            <FadeIn delay={0.3}>
              <ul className="mt-8 space-y-4">
                {limeFeatures.map((feat) => (
                  <li key={feat} className="flex items-start gap-3 text-[18px] font-[320] leading-[1.45] text-black">
                    <Check className="mt-0.5 h-5 w-5 shrink-0 text-black/60" />
                    <span>{feat}</span>
                  </li>
                ))}
              </ul>
            </FadeIn>
            <FadeIn delay={0.4}>
              <div className="mt-10">
                <FigmaButton variant="primary" href="/signup">
                  Start practicing now
                  <ArrowRight className="h-4 w-4" />
                </FigmaButton>
              </div>
            </FadeIn>
          </div>
        </ColorBlock>
      </section>

      {/* ===== COLOR BLOCK NAVY ===== */}
      <section className="py-24">
        <ColorBlock variant="navy">
          <div className="mx-auto max-w-4xl">
            <FadeIn>
              <p className="text-[18px] font-[400] font-mono uppercase tracking-[0.54px] text-white/40">
                Track your growth
              </p>
            </FadeIn>
            <FadeIn delay={0.1}>
              <h2 className="mt-4 text-[26px] font-[540] leading-[1.35] tracking-[-0.26px] text-white">
                Your progress, your way
              </h2>
            </FadeIn>
            <FadeIn delay={0.2}>
              <p className="mt-4 text-[20px] font-[330] leading-[1.40] tracking-[-0.14px] text-white/60 max-w-2xl">
                Detailed analytics, performance trends, and skill breakdowns help you 
                identify strengths and target areas for improvement.
              </p>
            </FadeIn>
            <FadeIn delay={0.3}>
              <div className="mt-10 grid grid-cols-2 gap-6 md:grid-cols-4">
                {navyStats.map((stat) => (
                  <div key={stat.label} className="text-center">
                    <p className="text-[48px] md:text-[64px] font-[340] leading-[1.10] tracking-[-0.96px] text-white">
                      {stat.value}
                    </p>
                    <p className="mt-2 text-[16px] font-[330] text-white/50">
                      {stat.label}
                    </p>
                  </div>
                ))}
              </div>
            </FadeIn>
          </div>
        </ColorBlock>
      </section>

      {/* ===== COLOR BLOCK CORAL ===== */}
      <section className="py-24">
        <ColorBlock variant="coral">
          <div className="mx-auto max-w-4xl">
            <FadeIn>
              <p className="text-[18px] font-[400] font-mono uppercase tracking-[0.54px] text-black/40">
                For developers, by developers
              </p>
            </FadeIn>
            <FadeIn delay={0.1}>
              <h2 className="mt-4 text-[26px] font-[540] leading-[1.35] tracking-[-0.26px] text-black">
                Technical interview mastery
              </h2>
            </FadeIn>
            <FadeIn delay={0.2}>
              <p className="mt-4 text-[20px] font-[330] leading-[1.40] tracking-[-0.14px] text-black/70 max-w-2xl">
                From coding challenges to system design, our platform covers every aspect 
                of the technical interview process.
              </p>
            </FadeIn>
            <FadeIn delay={0.3}>
              <div className="mt-10 grid gap-4 md:grid-cols-3">
                {coralFeatures.map((feat) => (
                  <div key={feat.title} className="rounded-[8px] bg-white/50 p-6">
                    <div className="mb-3 inline-flex rounded-full bg-white p-2.5">
                      <feat.icon className="h-5 w-5 text-black" />
                    </div>
                    <h3 className="text-[18px] font-[480] leading-[1.40] tracking-[-0.10px] text-black">
                      {feat.title}
                    </h3>
                    <p className="mt-1 text-[16px] font-[330] leading-[1.45] text-black/60">
                      {feat.desc}
                    </p>
                  </div>
                ))}
              </div>
            </FadeIn>
          </div>
        </ColorBlock>
      </section>

      {/* ===== FINAL CTA ===== */}
      <section className="py-24">
        <div className="mx-auto max-w-4xl px-4 text-center">
          <FadeIn>
            <h2 className="text-[48px] md:text-[64px] font-[340] leading-[1.10] tracking-[-0.96px] text-black">
              Ready to start?
            </h2>
          </FadeIn>
          <FadeIn delay={0.15}>
            <p className="mx-auto mt-6 max-w-xl text-[20px] font-[330] leading-[1.40] tracking-[-0.14px] text-black/60">
              Join thousands of successful candidates who prepared with MockAI. Start practicing today.
            </p>
          </FadeIn>
          <FadeIn delay={0.3}>
            <div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row">
              <FigmaButton variant="primary" href="/signup">
                Get started for free
                <ArrowRight className="h-4 w-4" />
              </FigmaButton>
              <FigmaButton variant="secondary" href="/interview">
                View demo
              </FigmaButton>
            </div>
          </FadeIn>
        </div>
      </section>

      <Footer />
    </div>
  )
}
