'use client'

import { useState, useEffect, useRef } from 'react'
import Link from 'next/link'
import { motion, useInView } from 'framer-motion'
import {
  Brain, MessageSquare, BarChart3, Briefcase, Shield, Clock,
  Check, ArrowRight, Code, Target, Sparkles, Zap, Star, Users,
  TrendingUp
} from 'lucide-react'
import { TopNav } from '@/components/ui/top-nav'
import { FigmaButton } from '@/components/ui/figma-button'
import { Footer } from '@/components/ui/footer'

const features = [
  {
    icon: Brain,
    title: 'AI Interview Questions',
    description: 'Dynamic questions generated by AI based on your role, experience, and target company.',
  },
  {
    icon: MessageSquare,
    title: 'Real-time Feedback',
    description: 'Instant feedback on your responses with detailed analysis of content and delivery.',
  },
  {
    icon: BarChart3,
    title: 'Performance Analytics',
    description: 'Comprehensive analytics tracking your progress across multiple dimensions.',
  },
  {
    icon: Briefcase,
    title: 'Role-based Interviews',
    description: 'Tailored interviews for specific roles from SWE to Product Management.',
  },
  {
    icon: Shield,
    title: 'AI Scoring',
    description: 'Multi-dimensional scoring evaluating clarity, relevance, depth, and confidence.',
  },
  {
    icon: Clock,
    title: 'Timed Practice',
    description: 'Real interview pressure with timed sessions and countdown reminders.',
  },
]

const limeFeatures = [
  'Role-specific question banks for every position',
  'Real-time AI feedback on your responses',
  'Performance scoring across multiple dimensions',
  'Company-specific interview preparation',
]

const navyStats = [
  { value: '50K+', label: 'Mock Interviews' },
  { value: '98%', label: 'Success Rate' },
  { value: '500+', label: 'Companies' },
  { value: '10K+', label: 'Active Users' },
]

const coralFeatures = [
  { icon: Code, title: 'Technical Interviews', desc: 'Data structures, algorithms, system design, and coding challenges' },
  { icon: Zap, title: 'System Design Prep', desc: 'Practice designing scalable systems with real-world scenarios' },
  { icon: Target, title: 'Behavioral Coaching', desc: 'STAR method training with personalized feedback loops' },
]

const companyItems = ['Google', 'Meta', 'Amazon', 'Microsoft', 'Apple', 'Netflix', 'Stripe', 'Spotify']

function FadeIn({ children, delay = 0, className }: {
  children: React.ReactNode
  delay?: number
  className?: string
}) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 24 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: '-80px' }}
      transition={{ duration: 0.6, delay, ease: [0.25, 0.4, 0.25, 1] as const }}
      className={className}
    >
      {children}
    </motion.div>
  )
}

function AnimatedCounter({ value }: { value: string }) {
  const ref = useRef<HTMLSpanElement>(null)
  const isInView = useInView(ref, { once: true })
  const [count, setCount] = useState(0)

  const num = parseInt(value.replace(/[^0-9]/g, ''))
  const suffix = value.replace(/[0-9]/g, '')

  useEffect(() => {
    if (!isInView) return
    let start = 0
    const increment = num / 60
    const timer = setInterval(() => {
      start += increment
      if (start >= num) {
        setCount(num)
        clearInterval(timer)
      } else {
        setCount(Math.floor(start))
      }
    }, 16)
    return () => clearInterval(timer)
  }, [isInView, num])

  return <span ref={ref}>{isInView ? `${count}${suffix}` : `0${suffix}`}</span>
}

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: { staggerChildren: 0.08, delayChildren: 0.1 },
  },
}

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: [0.25, 0.4, 0.25, 1] as const } },
}

export default function LandingPage() {
  return (
    <div className="w-full min-h-screen bg-[#fcfcff]">
      <TopNav />

      {/* ===== HERO ===== */}
      <section className="relative flex min-h-screen flex-col items-center justify-center px-4 pt-24 overflow-hidden">
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute top-1/4 -left-32 w-[500px] h-[500px] bg-gradient-to-br from-[#FF4D9D]/10 via-[#C084FC]/10 to-[#8B5CF6]/10 rounded-full blur-3xl animate-blob" />
          <div className="absolute top-1/3 -right-32 w-[400px] h-[400px] bg-gradient-to-br from-[#C084FC]/15 to-[#8B5CF6]/10 rounded-full blur-3xl animate-blob" style={{ animationDelay: '2s' }} />
          <div className="absolute -bottom-32 left-1/4 w-[600px] h-[300px] bg-gradient-to-br from-[#FF4D9D]/5 to-[#C084FC]/10 rounded-full blur-3xl animate-blob" style={{ animationDelay: '4s' }} />
        </div>

        <div className="mx-auto max-w-5xl text-center relative z-10">
          <FadeIn>
            <motion.div
              whileHover={{ scale: 1.05 }}
              className="mb-8 inline-flex items-center gap-2 rounded-full border border-[#C084FC]/20 bg-white/60 backdrop-blur-sm px-4 py-1.5 text-xs font-medium text-[#8B5CF6] shadow-sm"
            >
              <Sparkles className="h-3.5 w-3.5 text-[#FF4D9D]" />
              AI Mock Interviews
            </motion.div>
          </FadeIn>

          <FadeIn delay={0.15}>
            <h1 className="text-5xl sm:text-6xl lg:text-7xl font-bold tracking-tight bg-gradient-to-r from-[#FF4D9D] via-[#C084FC] to-[#8B5CF6] bg-clip-text text-transparent animate-gradient-rotate leading-[1.1]">
              Ace Your Next<br />Interview With AI
            </h1>
          </FadeIn>

          <FadeIn delay={0.3}>
            <p className="mx-auto mt-6 max-w-2xl text-lg sm:text-xl text-[#6b6a7a] leading-relaxed">
              Practice with real-time AI-powered mock interviews. Get instant feedback, track your progress, and land your dream job.
            </p>
          </FadeIn>

          <FadeIn delay={0.45}>
            <div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row">
              <FigmaButton className="bg-gradient-to-r from-[#FF4D9D] to-[#8B5CF6] min-w-[140px]" variant="primary" asChild>
                <Link href="/signup">
                  Sign up
                  <ArrowRight className="h-4 w-4" />
                </Link>
              </FigmaButton>
              <FigmaButton variant="secondary" asChild>
                <Link href="/interview">
                  View demo
                </Link>
              </FigmaButton>
            </div>
          </FadeIn>

          <FadeIn delay={0.6}>
            <div className="mt-24">
              <p className="mb-6 text-sm text-[#a0a0b0]">
                Trusted by candidates from leading companies
              </p>
              <motion.div
                variants={containerVariants}
                initial="hidden"
                whileInView="visible"
                viewport={{ once: true }}
                className="flex flex-wrap items-center justify-center gap-3"
              >
                {companyItems.map((company) => (
                  <motion.span
                    key={company}
                    variants={itemVariants}
                    whileHover={{ scale: 1.05, y: -2 }}
                    className="inline-flex items-center rounded-full border border-[#e8e7f0] bg-white px-4 py-1.5 text-sm font-medium text-[#6b6a7a] shadow-sm transition-all duration-300 hover:border-[#C084FC]/30 hover:text-[#8B5CF6] hover:shadow-md hover:shadow-[#C084FC]/10"
                  >
                    {company}
                  </motion.span>
                ))}
              </motion.div>
            </div>
          </FadeIn>
        </div>
      </section>

      {/* ===== FEATURES ===== */}
      <section className="relative py-24">
        <div className="absolute inset-0 bg-gradient-to-b from-[#fcfcff] via-[#f5f0ff]/30 to-[#fcfcff] pointer-events-none" />
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 relative z-10">
          <FadeIn>
            <div className="text-center">
              <motion.div
                whileHover={{ scale: 1.05 }}
                className="mb-4 inline-flex items-center gap-2 rounded-full border border-[#C084FC]/20 bg-white/60 backdrop-blur-sm px-4 py-1.5 text-xs font-medium text-[#8B5CF6] shadow-sm"
              >
                <Star className="h-3.5 w-3.5 text-[#FF4D9D]" />
                Features
              </motion.div>
              <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-[#0a0a0f]">
                Everything you need to prepare
              </h2>
              <p className="mt-3 text-lg text-[#6b6a7a] max-w-2xl mx-auto">
                AI-powered tools designed to simulate real interview experiences and accelerate your growth.
              </p>
            </div>
          </FadeIn>

          <div className="mt-16 grid gap-5 md:grid-cols-2 lg:grid-cols-3">
            {features.map((feature, index) => (
              <FadeIn key={feature.title} delay={index * 0.05}>
                <motion.div
                  whileHover={{ y: -6, boxShadow: '0 20px 40px rgba(192, 132, 252, 0.12)' }}
                  transition={{ type: "spring", stiffness: 300, damping: 20 }}
                  className="group relative overflow-hidden rounded-2xl border border-[#e8e7f0] bg-white p-6 transition-all duration-300"
                >
                  <div className="absolute inset-0 bg-gradient-to-br from-[#FF4D9D]/5 via-[#C084FC]/5 to-[#8B5CF6]/5 opacity-0 transition-opacity duration-300 group-hover:opacity-100" />
                  <div className="relative mb-4 inline-flex rounded-xl bg-gradient-to-br from-[#FF4D9D] to-[#8B5CF6] p-3 shadow-lg shadow-[#C084FC]/25">
                    <feature.icon className="h-5 w-5 text-white" />
                  </div>
                  <h3 className="relative mb-2 text-xl font-semibold text-[#0a0a0f]">
                    {feature.title}
                  </h3>
                  <p className="relative text-base text-[#6b6a7a] leading-relaxed">
                    {feature.description}
                  </p>
                </motion.div>
              </FadeIn>
            ))}
          </div>
        </div>
      </section>

      {/* ===== BUILT FOR EVERY ROLE ===== */}
      <section className="relative py-24 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-[#f5f0ff] via-white to-[#fdf2f8] pointer-events-none" />
        <div className="absolute top-0 right-0 w-96 h-96 bg-gradient-to-bl from-[#C084FC]/10 to-transparent rounded-full blur-3xl pointer-events-none" />
        <div className="absolute bottom-0 left-0 w-96 h-96 bg-gradient-to-tr from-[#FF4D9D]/10 to-transparent rounded-full blur-3xl pointer-events-none" />
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 relative z-10">
          <FadeIn>
            <motion.div
              whileHover={{ scale: 1.05 }}
              className="mb-4 inline-flex items-center gap-2 rounded-full border border-[#C084FC]/20 bg-white/60 backdrop-blur-sm px-4 py-1.5 text-xs font-medium text-[#8B5CF6] shadow-sm"
            >
              <Users className="h-3.5 w-3.5 text-[#FF4D9D]" />
              Built for every role
            </motion.div>
          </FadeIn>
          <FadeIn delay={0.1}>
            <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-[#0a0a0f]">
              Real interviews, real confidence
            </h2>
          </FadeIn>
          <FadeIn delay={0.2}>
            <p className="mt-4 text-lg text-[#6b6a7a] leading-relaxed max-w-2xl">
              Our AI platform simulates real interview environments with role-specific questions,
              timed responses, and instant feedback. Practice until you&apos;re ready for the real thing.
            </p>
          </FadeIn>
          <FadeIn delay={0.3}>
            <ul className="mt-10 space-y-4">
              {limeFeatures.map((feat) => (
                <motion.li
                  key={feat}
                  whileHover={{ x: 4 }}
                  className="flex items-start gap-4 text-lg text-[#0a0a0f]"
                >
                  <span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-[#FF4D9D] to-[#8B5CF6]">
                    <Check className="h-3.5 w-3.5 text-white" />
                  </span>
                  <span>{feat}</span>
                </motion.li>
              ))}
            </ul>
          </FadeIn>
          <FadeIn delay={0.4}>
            <div className="mt-10">
              <FigmaButton className="bg-gradient-to-r from-[#FF4D9D] to-[#8B5CF6]" variant="primary" asChild>
                <Link href="/signup">
                  Start practicing now
                  <ArrowRight className="h-4 w-4" />
                </Link>
              </FigmaButton>
            </div>
          </FadeIn>
        </div>
      </section>

      {/* ===== TRACK YOUR GROWTH / STATS ===== */}
      <section className="relative py-24 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-[#0f0c29] via-[#1a1a2e] to-[#16213e]" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-gradient-to-br from-[#C084FC]/10 to-[#8B5CF6]/5 rounded-full blur-3xl pointer-events-none" />
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 relative z-10 text-center">
          <FadeIn>
            <motion.div
              whileHover={{ scale: 1.05 }}
              className="mb-4 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 backdrop-blur-sm px-4 py-1.5 text-xs font-medium text-white/70 shadow-sm"
            >
              <TrendingUp className="h-3.5 w-3.5 text-[#C084FC]" />
              Track your growth
            </motion.div>
          </FadeIn>
          <FadeIn delay={0.1}>
            <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-white">
              Your progress, your way
            </h2>
          </FadeIn>
          <FadeIn delay={0.2}>
            <p className="mt-4 text-lg text-white/60 leading-relaxed max-w-2xl mx-auto">
              Detailed analytics, performance trends, and skill breakdowns help you
              identify strengths and target areas for improvement.
            </p>
          </FadeIn>
          <FadeIn delay={0.3}>
            <div className="mt-14 grid grid-cols-2 gap-8 md:grid-cols-4">
              {navyStats.map((stat) => (
                <motion.div
                  key={stat.label}
                  whileHover={{ y: -4 }}
                  className="relative group"
                >
                  <div className="absolute inset-0 bg-gradient-to-b from-white/5 to-transparent rounded-2xl opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
                  <div className="relative">
                    <p className="text-4xl sm:text-5xl font-bold bg-gradient-to-r from-[#FF4D9D] via-[#C084FC] to-[#8B5CF6] bg-clip-text text-transparent">
                      <AnimatedCounter value={stat.value} />
                    </p>
                    <p className="mt-2 text-sm text-white/50">
                      {stat.label}
                    </p>
                  </div>
                </motion.div>
              ))}
            </div>
          </FadeIn>
        </div>
      </section>

      {/* ===== TECHNICAL INTERVIEW MASTERY ===== */}
      <section className="relative py-24 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-[#fef2f2] via-white to-[#fff7ed] pointer-events-none" />
        <div className="absolute -top-32 -right-32 w-96 h-96 bg-gradient-to-bl from-[#FF4D9D]/10 to-transparent rounded-full blur-3xl pointer-events-none" />
        <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="text-center">
            <FadeIn>
              <motion.div
                whileHover={{ scale: 1.05 }}
                className="mb-4 inline-flex items-center gap-2 rounded-full border border-[#C084FC]/20 bg-white/60 backdrop-blur-sm px-4 py-1.5 text-xs font-medium text-[#8B5CF6] shadow-sm"
              >
                <Code className="h-3.5 w-3.5 text-[#FF4D9D]" />
                For developers, by developers
              </motion.div>
            </FadeIn>
            <FadeIn delay={0.1}>
              <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-[#0a0a0f]">
                Technical interview mastery
              </h2>
            </FadeIn>
            <FadeIn delay={0.2}>
              <p className="mt-4 text-lg text-[#6b6a7a] leading-relaxed max-w-2xl mx-auto">
                From coding challenges to system design, our platform covers every aspect
                of the technical interview process.
              </p>
            </FadeIn>
          </div>

          <div className="mt-14 grid gap-6 md:grid-cols-3">
            {coralFeatures.map((feat, index) => (
              <FadeIn key={feat.title} delay={0.2 + index * 0.1}>
                <motion.div
                  whileHover={{ y: -6, boxShadow: '0 20px 40px rgba(192, 132, 252, 0.12)' }}
                  transition={{ type: "spring", stiffness: 300, damping: 20 }}
                  className="group relative overflow-hidden rounded-2xl border border-[#e8e7f0] bg-white p-6 transition-all duration-300"
                >
                  <div className="absolute inset-0 bg-gradient-to-br from-[#FF4D9D]/5 via-[#C084FC]/5 to-[#8B5CF6]/5 opacity-0 transition-opacity duration-300 group-hover:opacity-100" />
                  <div className="relative mb-4 inline-flex rounded-xl bg-gradient-to-br from-[#FF4D9D] to-[#8B5CF6] p-3 shadow-lg shadow-[#C084FC]/25">
                    <feat.icon className="h-5 w-5 text-white" />
                  </div>
                  <h3 className="relative mb-2 text-xl font-semibold text-[#0a0a0f]">
                    {feat.title}
                  </h3>
                  <p className="relative text-base text-[#6b6a7a] leading-relaxed">
                    {feat.desc}
                  </p>
                </motion.div>
              </FadeIn>
            ))}
          </div>
        </div>
      </section>

      {/* ===== FINAL CTA ===== */}
      <section className="relative py-24 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-[#f5f0ff] via-[#fcfcff] to-[#fdf2f8] pointer-events-none" />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[400px] bg-gradient-to-br from-[#FF4D9D]/5 via-[#C084FC]/5 to-[#8B5CF6]/5 rounded-full blur-3xl pointer-events-none" />
        <div className="mx-auto max-w-4xl px-4 text-center relative z-10">
          <FadeIn>
            <h2 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight bg-gradient-to-r from-[#FF4D9D] via-[#C084FC] to-[#8B5CF6] bg-clip-text text-transparent animate-gradient-rotate">
              Ready to start?
            </h2>
          </FadeIn>
          <FadeIn delay={0.15}>
            <p className="mx-auto mt-6 max-w-2xl text-lg text-[#6b6a7a] leading-relaxed">
              Join thousands of successful candidates who prepared with MockAI. Start practicing today.
            </p>
          </FadeIn>
          <FadeIn delay={0.3}>
            <div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row">
              <FigmaButton className="bg-gradient-to-r from-[#FF4D9D] to-[#8B5CF6]" variant="primary" asChild>
                <Link href="/signup">
                  Sign up
                  <ArrowRight className="h-4 w-4" />
                </Link>
              </FigmaButton>
              <FigmaButton variant="secondary" asChild>
                <Link href="/interview">
                  View demo
                </Link>
              </FigmaButton>
            </div>
          </FadeIn>
        </div>
      </section>

      <Footer />
    </div>
  )
}
